name: GitHub README Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "23 */6 * * *"

jobs:
  github_readme_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download github readme stats
        run: |
          curl -v -o ./default.svg     -fsSL "https://github-readme-stats-x.vercel.app/api?username=xjasonlyu&show_icons=true&count_private=true&hide_border=true&include_all_commits=true&theme=default"
          curl -v -o ./github_dark.svg -fsSL "https://github-readme-stats-x.vercel.app/api?username=xjasonlyu&show_icons=true&count_private=true&hide_border=true&include_all_commits=true&theme=github_dark"

      - name: Upload github readme stats
        run: |
          git config --global user.name  'xjasonlyu'
          git config --global user.email 'xjasonlyu@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}

          mkdir -p ./stats/
          mv *.svg ./stats/

          git add stats/*.svg
          git commit -m "Update github-readme-stats to \`$(date -u '+%Y.%-m%d.%-H%M.%-S')\`" && git push origin main || echo "nothing to commit"
