name: Metrics
on:
  schedule: [{cron: "0 12 * * *"}]
  workflow_dispatch:
  push:
    branches: ["master", "main"]
    paths: [".github/workflows/metrics.yml"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: xjasonlyu
          template: classic
          base: header
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_languages_ignored: c
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_filter: stars:>500
          plugin_notable_types: commit,pull_request,issue
